### PR TITLE
Changed Travis CI to use FluentMigrator.sln

### PR DESCRIPTION
**Pull request by escarls**
- moved the build parameters from CI.proj to parameters in .travis.yml
- removed CI.proj as it's no longer in use (no references from any file).
- Added the missing projects from FluentMigrator (2010).sln.
- Set the build config for FluentMigrator.sln to the same as FluentMigrator (2010).sln, except for the changes to FluentMigrator.sln from checkins.
- Fixed some build warnings.

The Travis CI logs are now the same as they were before the changes, except for some fewer warnings.
The Nant logs (build.bat) are the same as they were before the changes, except for some fewer warnings.
Rake still builds equal nuget packages.

### CODE REVIEW

**Comment by escarls** [comment]
Hmm... Seems the TeamCity server only builds from branches or just from master.
Any chance someone could setup a branch that I can test to switch the Nant build to use FluentMigrator.sln file, so we can get rid of the FluentMigrator (2010).sln file?

**Comment by fubar-coder** [comment]
I created a branch called `ci-test`

**Comment by escarls** [comment]
The current PR didn't break the Nant build on the TeamCity server.
[New build](https://teamcity.jetbrains.com/viewLog.html?buildId=994418&buildTypeId=bt82&tab=buildLog) [old build](https://teamcity.jetbrains.com/viewLog.html?buildId=991559&buildTypeId=bt82&tab=buildLog)
Just some fewer warnings.

**Comment by escarls** [comment]
Part of the PRs to solve #738

**Comment by fubar-coder** [comment]
Obsolete since the switch to .NET Core 2.0/msbuild tooling

**Pull request closed without merging**
