### PR TITLE
Create Foreign Key with SQLite

### PR DESCRIPTION
**Pull request by STVM**
concerning issue #356

I put things concerning FK in ColumnBase

### CODE REVIEW

**Comment by fubar-coder** [comment]
@tommarien Schedule for 1.6.2 or 1.7.0? Could this be a potential breaking change?

**Comment by NikGovorov** [comment]
+1.

**Comment by Serg046** [comment]
Please release...

**Comment by Rowandish** [comment]
+1 please..

**Comment by fubar-coder** [comment]
Your changes have been incorporated into the release/2.0.0 branch

**Pull request closed without merging**
