### PR TITLE
dev-494 add delete.Table.IfExists() syntax and support generators

### PR DESCRIPTION
**Pull request by RobPethick**
#494 I have only added Delete.Table.IfExists() for now but I'll work on the equivalent for other objects once this PR gets through (just so I don't do a lot of work in the wrong direction)

### CODE REVIEW

**Comment by fubar-coder** [comment]
LGTM :+1:

**Comment by jzabroski** [comment]
@fubar-coder  Does this PR need to be updated to get @RobPethick  changes merged in?

**Comment by fubar-coder** [comment]
The PR has to be ported manually - just like I did with several others 😓 .

**Comment by jzabroski** [comment]
@fubar-coder  Right - I could help with that.

**Comment by jzabroski** [comment]
@RobPethick It's been about a decade, but your PR is finally being merged indirectly via https://github.com/fluentmigrator/fluentmigrator/commit/b758e9cbbc8d2e625cf470d7d604ce57236b4e30

**Comment by RobPethick** [comment]
Many thanks @jzabroski - a real trip down memory lane getting a ping on this one!

**Comment by brendangooden** [comment]
@RobPethick  Thanks for your work on this! I was literally just looking at implementing this myself. 
Have you begun and/or completed any work on the additional deletes e.g. `Foreign Key`, `Index`, `Constraint` etc?

**Comment by jzabroski** [comment]
@brendangooden this PR was ten years old. I manually merged it in. No, we have not. Happy to take a PR

**Pull request closed without merging**
