### PR TITLE
Postgres add support for tablespace

### PR DESCRIPTION
**Pull request by lillo42**
Add support for tablespace in index

### CODE REVIEW

**Review by jzabroski — CHANGES_REQUESTED** [review]
@lillo42 Would you have an appetite to tackle this for all DBMSes that support tablespace and/or filegroup(s)?  There are a lot of them outlined in #967

**Comment by lillo42** [comment]
@jzabroski Yes, I would like to tackle that in the future, now I'm focus on PostgreSQL missing feature(like ~~index~~/create extensions/improve table feature)

**Comment by jzabroski** [comment]
OK, So is the plan that at some point, we would do a major release where we move the namespace for Tablespace from Postgres into the global namespace?  Unless I missed it, your current proposal doesnt have  a Create.Tablespace root item.  So, would people just call Execute.Sql to create the tablespace?

**Comment by lillo42** [comment]
> OK, So is the plan that at some point, we would do a major release where we move the namespace for Tablespace from Postgres into the global namespace? 

I don't know if is necessary to be major release to do it, but we can move it to from Postgres into the global namespace or create direct in the global namespace.

> Unless I missed it, your current proposal doesnt have a Create.Tablespace root item. So, would people just call Execute.Sql to create the tablespace? If so, I suggest we update the summary docs to explain that is the approach for now

Thinking better now, it's feature isn't so necessary, maybe more for DBA, so I believe this feature can we for tablespace implementation.

**Comment by jzabroski** [comment]
I will try to merge this tomorrow.  Got super busy with deadlines at work.

**Comment by jzabroski** [comment]
@lillo42 Sorry I've been so tied up with work.  Will get to this by this weekend. This is my last week before vacation

**Pull request merged**
