### PR TITLE
Sqlite rename column

### PR DESCRIPTION
**Pull request by Chandler-Davidson**
Related to #1290 

Let me know if we should add versioning to the SQLite generator.

### CODE REVIEW

**Comment by jzabroski** [comment]
I think we should just merge this and see if anyone complains about using it on an older version of SQLite, rather than do the version check.  I suspect if you're running SQLite you're upgrading frequently, but I could be wrong.

**Comment by jzabroski** [comment]
@Chandler-Davidson can you fix this test? https://github.com/fluentmigrator/fluentmigrator/pull/1291/files#annotation_275527805

**Comment by Chandler-Davidson** [comment]
@jzabroski, sorry, just fixed the test! I agree about the use of SQLite. If you're moving to use FluentMigrator, you're probably in a position to also upgrade the version of SQLite.

**Comment by igitur** [comment]
This is closed, but I noticed that this PR *adds* the `Microsoft.Data.Sqlite` dependency to some projects that did not have the dependency before. Example : https://github.com/fluentmigrator/fluentmigrator/blob/4bacf0cd2a225d6f36c41931c774c7a52d2cdce6/src/FluentMigrator.Abstractions/FluentMigrator.Abstractions.csproj#L45

Was this intentional? 

I noticed this now when I upgrade my Nuget package and got a whole lot of SQlite packages referenced that don't think I need at all.

**Comment by jzabroski** [comment]
@igitur No, that was not intentional.  I have no idea how I missed that.  I must not have reviewed the last commit.  If you want to submit a PR to remove those obviously wrong dependencies, I'll merge it and release 3.2.9 tonight.

**Comment by igitur** [comment]
Usually I have no problem submitting PRs, but I'll give the author who introduced the error first chance to correct it. Hope that's OK?

**Comment by jzabroski** [comment]
Sure.  @Chandler-Davidson - any interest in fixing this?  The problem seems to be this commit: https://github.com/fluentmigrator/fluentmigrator/pull/1291/commits/12bf2f165b6eca6b469ef8ec2012e4110289513d - A bunch Sqlite packages got added to various projects.

**Comment by Chandler-Davidson** [comment]
@igitur, I'm out of the office for a bit, so go ahead! Sorry for the extra work.

**Comment by igitur** [comment]
Ok, I'll do a PR. Do I base it on `master` or `develop` ?

**Comment by jzabroski** [comment]
`master`.  Thank you.

**Pull request merged**
