### PR TITLE
Remove ExplicitUnicodeString and add NonUnicodeString

### PR DESCRIPTION
**Pull request by vgrigoriu**
As I explained [here](https://github.com/schambers/fluentmigrator/issues/636#issuecomment-129391177), code generatiion for SQL Server should default to Unicode string literals, so I removed `ExplicitUnicodeString` and added `NonUnicodeString` instead.

This change affected SQL Server CE too, which I think defaults to Unicode, so `'caș'` and `N'caș'` are equivalent there, but there shouldn't be any harm in using `N'`.

Hana was also using `ExplicitUnicodeString`, so I went ahead and changed it too. @FabioNascimento, is it ok if the Hana generator dafaults to Unicode string literals?

I removed the `ExplicitUnicodeString` class. This means people who were using it will have to change their code. I can add it back and deprecate it if anyone will miss it, but I think migration code is cleaner when you use normal .NET strings.

### CODE REVIEW

**Comment by vgrigoriu** [comment]
Fixes #636.

**Comment by FabioNascimento** [comment]
Hello @vgrigoriu ,

Sorry for the late answer, but I just see now. I test your changes in HANA db and everything work fine...

Fabio

**Comment by vgrigoriu** [comment]
Wow, that's a blast from the past 😃 
Who is taking care of this repo now? @fubar-coder ? Any chance of merging this in if I solve the conflicts?

**Comment by fubar-coder** [comment]
This seems to be a breaking change for the end user due to the removal of `ExplicitUnicodeString`. Can you please keep `ExplicitUnicodeString` as obsolete (with explanation)? Can it cause problems when we switch to unicode by default?

**Comment by vgrigoriu** [comment]
All right, I'll put `ExplicitUnicodeString` back in as obsolete.

I explained [here|https://github.com/schambers/fluentmigrator/issues/636#issuecomment-129391177] what I think are the consequences of switching to Unicode.

**Comment by fubar-coder** [comment]
Also, please don't forget to handle `ExplicitUnicodeString` instances 😉 .

@schambers, I guess, that this change is OK for a minor library update when the only user visible change is a deprecated class?

**Comment by vgrigoriu** [comment]
Here you are.

**Comment by fubar-coder** [comment]
Thank you

**Pull request closed without merging**
