### PR TITLE
Make TypeMap Injectable #1755

### PR DESCRIPTION
**Pull request by jzabroski**
Fixes https://github.com/fluentmigrator/fluentmigrator/issues/1063, https://github.com/fluentmigrator/fluentmigrator/issues/1724 and https://github.com/fluentmigrator/fluentmigrator/issues/1618.

Possible breaking changes include:

* `ColumnBase` now raises an obsolete warning: "Use ColumnBase instead. Going forward, column models must have a db-specific type map model."
* Various Generators have new constructor signatures added or replaced to support database-specific type maps.

### CODE REVIEW

**Comment by jzabroski** [comment]
I've submitted a community support request here: https://github.com/orgs/community/discussions/114175

**Comment by jzabroski** [comment]
If I can't get this working, I may pivot to using GitHub Actions to directly trigger the Azure DevOps Pipeline: https://learn.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-161-update

It's not clear to me that will actually work, but it's _something_. @eloekset Any thoughts on this approach? "Gross", maybe? :)

@schambers If you could pull down this PR and tell me if all the tests pass on your machine, that would be helpful, too...

**Comment by eloekset** [comment]
I'm not sure what has happened, but it looks like it doesn't help triggering the build manually. I triggered it on the main branch referring to the latest commit of this PR, and the checks ran successfully, but the status is not reported back here, so I guess we'll just have to merge the PR without waiting for the requirements to be met.

https://dev.azure.com/fluentmigrator/fluentmigrator/_build/results?buildId=856&view=results

**Comment by jzabroski** [comment]
How did you trigger it manually?  I couldnt see how to trigger a specific commit through the UI.

**Comment by jzabroski** [comment]
@eloekset Actually, what you did worked - see this screenshot.  But the overall PR status is still gated because not all commits in the chain got "built" even if they one is a no-op (fast forward merge) and the other is updating the README.md (which I did as an attempt to see if that would force the process to heal itself + finally fix at README file). 

image

**Comment by eloekset** [comment]
> How did you trigger it manually? I couldnt see how to trigger a specific commit through the UI.

You have to sign in to see the **Run pipeline** button. I added you and Mark to the **Build Administrators** group in case you need more rights to administer build pipelines.

I selected the **main** branch and then copied the commit ID from the last commit in this PR. 
image

**Comment by jzabroski** [comment]
@eloekset Thanks, It didn't occur to me that conceptually a PR commit was part of the main branch.

**Pull request merged**
