### PR TITLE
Fixing Oracle identity column type issues #1040

### PR DESCRIPTION
**Pull request by BigYellowHammer**
Implemented changes suggested by @fubar-coder in #1040 

> The problems should be fixed by making the following changes:
> - Changing object to long in OracleExtensions, line 120
> - Changing long? to int? in Oracle12CColumn, line 61.

### CODE REVIEW

**Comment by fubar-coder** [comment]
@BigYellowHammer Ok, so my suggestions in #1040 do work? I haven't tested them myself.

**Comment by BigYellowHammer** [comment]
Now they work :)
Your suggestions fixed casting issue, but there was another one with how identity options were generated.

According to oracle documentation
https://docs.oracle.com/database/121/SQLRF/img_text/identity_options.htm
those options should looks as follows
`(START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 50)`

I made small changes in `Oracle12CColumn` class and now this code
`expression.Identity(OracleGenerationType.ByDefault, 1, 1, 1, 50);`
is generating such SQL
` GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 50),`

Tested both methods from 'OracleExtensions' on Oracle 12C, works fine.

**Comment by fubar-coder** [comment]
Did I miss it or aren't there any unit tests for the generated identity column SQL?

**Comment by BigYellowHammer** [comment]
There are some in `Oracle12CColumnTests` but they are not setting AdditionalFeatures dictionary. I guess you want me to add something there

**Comment by fubar-coder** [comment]
Thank you for the unit tests, but I was just curious.

**Pull request merged**
