### PR TITLE
Add IMigrationRunner.LoadVersionInfoIfRequired()

### LINKED ISSUE #960: MigrationRunner.VersionLoader.LoadVersionInfo not executed in MigrationRunner constructor
Previously, in the constructors of `MigrationRunner` the `VersionLoader` property was constructor normally, but this has recently changed to a `new Lazy<IVersionLoader>(...)` implementation. 

The consequence is that `VersionLoader.LoadVersionInfo()` is not called when the `MigrationRunner` instance is constructed, but rather delayed. It would be called when `.MigrateUp()`, `MigrateDown()`, `Rollback()` or `RollbackToVersion()` is called.

However, these methods aren't the only ones that are used. For example, in my case, I'm constructing a `MigrationRunner` and deliberately using `runner.Up(migration)` to migrate only certain migrations. In my case, I deliberately want to exclude migrations related to seeding a database, but that's besides the point.

`MigrationRunner.Up()` doesn't call `VersionLoader.LoadVersionInfo()`, so the appropriate `VersionInfo` table is never created. And that creates other obvious problems.

My suggestion is to revert the lazy loading of `VersionLoader` to a normal constructor, or, alternatively, also call `VersionLoader.LoadVersionInfo()` in the other methods, where applicable. I can submit a PR, but I need your guidance first.

### PR DESCRIPTION
**Pull request by igitur**
Fixes #960

### CODE REVIEW

**Comment by fubar-coder** [comment]
Can you retarget this PR to `fluentmigrator/develop`?

**Comment by igitur** [comment]
ok, done.

**Comment by igitur** [comment]
@fubar-coder I don't understand what Codacy's issue is. The new method contains a reference to instance data (`VersionLoader`) therefore the new method cannot be static.

**Comment by fubar-coder** [comment]
Yeah, Codacy is sometimes wrong. Just ignore it.

**Pull request merged**
