### PR TITLE
Allow FluentMigrator to be used from an assembly

### PR DESCRIPTION
**Pull request by cguedel**
Based on http://manfredlange.blogspot.ch/2011/11/fluent-nhibernate-and-fluent-migrator.html
- I don't know if the original author of the InProc API intends to get this integrated.
- This code adds an InProc assembly & nuget package to start migration from an assembly

### CODE REVIEW

**Comment by jogibear9988** [comment]
Has this a chance of getting merged?

**Comment by tommarien** [comment]
@jogibear9988 i would love to integrate this but it needs some serious realignment ;)

**Comment by jogibear9988** [comment]
yeah, it's still not yet finished!

but maybe you can give tips what to realign!

Von meinem iPhone gesendet

**Comment by tommarien** [comment]
@jogibear9988 Alignment need would be

* Remove all Inproc assembly
* Include changes in runner
* Remove rake changes to create a new nuget ( as runner allready exists)

This is what comes in mind atm

**Comment by fubar-coder** [comment]
The cleanup should also include:

- No binary files in the pull request
- Rebase on latest development version
- Documentation what you want to achieve with this pull request
- Please avoid changing line endings

**Comment by marcrocny** [comment]
Why does this require a separate project? I (and [others](http://stackoverflow.com/questions/2751373/execute-fluentmigrator-migrations-from-code/15295377#15295377)) are doing this directly from FluentMigrator.Runner.

**Comment by fubar-coder** [comment]
Closed due to inactivity, the current runner is already usable from your project without calling an external executable.

**Pull request closed without merging**
