### PR TITLE
Postgres add support for nulls last/first on column

### PR DESCRIPTION
**Pull request by lillo42**

### CODE REVIEW

**Comment by jzabroski** [comment]
@lillo42 Shouldn't there be a test for Postgres10_0?  Otherwise, looks good to me.

**Comment by lillo42** [comment]
@jzabroski Why? I think isn't necessary because NULL FIRST/LAST was create in Postgres 8.3 (I think)

**Comment by jzabroski** [comment]
Got it.  I did not realize that.

**Comment by jzabroski** [comment]
Will try to release 3.2.11 today.

**Comment by lillo42** [comment]
@jzabroski before create a new release, please try to review and merge this other PR: https://github.com/fluentmigrator/fluentmigrator/pull/1399

**Pull request merged**
