### PR TITLE
ROWGUIDCOL on SqlServer

### PR DESCRIPTION
**Pull request by stsrki**
Added option to set ROWGUIDCOL attribute when creating table (SqlServer
only)

```
Create.Table( "TestTable" ).InSchema( "TestSchema" )
        .WithColumn( "TestTableID" ).AsGuid().RowGuid().PrimaryKey().WithDefault( SystemMethods.NewSequentialId ).NotNullable();
```

ps. I had to remove previous pull request because I messed something while trying to add another pull request.

### CODE REVIEW

**Comment by tommarien** [comment]
@stsrki Is it possible to add some tests for this feature ? also again i would advise to keep formatRowGuid only on sql server column class instead of adding it to columnbase

**Comment by stsrki** [comment]
Ok I will try to do it as soon as possible.

**Comment by stsrki** [comment]
Everything is moved to the SqlServer provider except for the IsRowGuid in ColumnDefinition class.

**Comment by stsrki** [comment]
I'm now trying to implement replication in PostgreSQL with Slony-I and it seems to have similar logic as SqlServer. They both require that there is a unique key contraint in the replicated table. In SqlServer it is ROWGUIDCOL and in PostgreSQL it is UNIQUE.
What do you recommend before I implement this in FluentMigrator? Do I still need to separate it for every provider or can I define it in ColumnBase. Maybe it can be later user for other database providers.

**Comment by tommarien** [comment]
@stsrki Why not use a sql server specific extension here AsRowGuid ?

**Comment by fubar-coder** [comment]
Are the unit tests the only thing that's missing?

**Comment by tommarien** [comment]
@fubar-coder seems to be ;)

**Comment by fubar-coder** [comment]
Your changes have been incorporated into the release/2.0.0 branch

**Pull request closed without merging**
