### PR TITLE
#1733: add readme for use in nuget readme documentation

### LINKED ISSUE #1733: fluentmigrator is missing NuGet package README file
We've noticed that your package on NuGet.org is missing a README file.

  ## Why READMEs are Important
  Our customer research indicates that one of the top problems that package consumers face is insufficient package documentation such as README files. Adding a README file to your package will help users quickly understand what the package is and what it does. Since your README will be the first impression for users when they view your package on NuGet.org, it is crucial for authors to write and include high-quality READMEs for their packages.

  ## Get Started with READMEs

  ### How to Add a README
  If you're new to NuGet READMEs, follow guidance on [how to add one to your package](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/).

  ### How to write high quality of READMEs
  Follow [a blog post](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/) with README best practices and a template file to help you get started. 

  ## We Value Your Feedback
  We value your feedback. If you encounter any issues or have suggestions, please reply to this issue.

  Thank you for your contribution to the NuGet community.

### PR DESCRIPTION
**Pull request by schambers**
Adds a readme doc that will strictly be used on the nuget project page located here https://www.nuget.org/packages/FluentMigrator

Fixes #1733

### CODE REVIEW

**Comment by schambers** [comment]
For your review @jzabroski

**Comment by jzabroski** [comment]
Shouldn't the Readme xml tag say - nuget in the filename? Have not closely read how this works.

**Comment by jzabroski** [comment]
https://github.com/NuGet/NuGet.Client/blob/dev/src%2FNuGet.Core%2FNuGet.Packaging%2Fcompiler%2Fresources%2Fnuspec.xsd

**Comment by jzabroski** [comment]
It looks like it needs to say:

```
                <readme>docs\README-nuget.md</readme>
	</metadata>
	<files>
		<file src="_._" target="content"/>
		<file src="tools/" />
		<file src="docs/README-nuget.md" target="docs" />
	</files>
</package>
```


Not done investigating.

**Comment by jzabroski** [comment]
Resolved last night.

**Pull request merged**
