### PR TITLE
Bugfix/1827 raw sql

### PR DESCRIPTION
**Pull request by PhenX**
A proposal to fix the #1827 issue

### CODE REVIEW

**Comment by jzabroski** [comment]
@PhenX The Postgres tests are failing due to the new code missing a trailing semi-colon at the end of the statement.  Any chance you can fix it?  I think we should include the semi-colon, to be clear, which I believe was the previous behavior.  One reason is preview-only mode scripts need a way to disambiguate grammar when used with ambiguous grammar keywords that start an Execute.Sql block.

**Comment by PhenX** [comment]
> @PhenX The Postgres tests are failing due to the new code missing a trailing semi-colon at the end of the statement.  Any chance you can fix it?  I think we should include the semi-colon, to be clear, which I believe was the previous behavior.  One reason is preview-only mode scripts need a way to disambiguate grammar when used with ambiguous grammar keywords that start an Execute.Sql block.

Yes I feared this detail would fail tests. I'll change the impacted expression. Did I do the right thing removing the overloads that did the same as the base class?

**Comment by jzabroski** [comment]
> Did I do the right thing removing the overloads that did the same as the base class?

I guess it depends if that is why it is breaking.  I am working on a PR to add an `ISeparator` interface to FluentMigrator to separate statements and statement batches. If we had that, we may not need customization per generator?

**Comment by PhenX** [comment]
@jzabroski I pushed the changes, but had to change a few tests for spacing and the condition "1 = 1" present for all other dbms, is that a problem?
Also, when does the pipeline run the checks?

**Comment by jzabroski** [comment]
There's some problem with the pipeline that appears to have started when I renamed the master branch to main. It seems like AzureDevOps still defaults to assuming master in many places.

i have been manually running builds against each pr head commit. Would love to figure this out.

**Comment by jzabroski** [comment]
My take on the Where 1 = 1 is it's an idiom used to silence static analysis tools like RedGate SQL Prompt that warn when a DML statement is missing a where clause. In this sense it makes sense to generate it for .AllRows()

**Comment by jzabroski** [comment]
I kicked off a CI build for this last commit.

**Comment by PhenX** [comment]
> I kicked off a CI build for this last commit.

Oh 😅 looks like I'm not done yet

**Pull request merged**
