### PR TITLE
Fix of #1265 OracleException ORA-01704 string literal too long

### PR DESCRIPTION
**Pull request by fairking**
Fix of #1265 
The issue was with end line characters. I have also added TABs just in case. Please feel free to review or edit if necessery.

### CODE REVIEW

**Comment by jzabroski** [comment]
So these are Oracle escape Characters, not C# escape Character, right? In other words the code was doing:
```sql
'Foo\' +
'nBar'
```

**Comment by fairking** [comment]
I am not sure. I did a quick fix and it works, but now I am starting to realize more:
It looks like it wasn't escaping end lines but adding extra 2 spaces to the left.
Why it was working with current changes?
Let see we got:
ABC{\r}{\n} (total 5 characters) based on my pr we must reduce the number of characters to 2
Result:
{space}{space}ABC{\r}{\n} (total 7 characters) (so two extra spaces are reduced by {\r}{\n} we subtracted.

Do you remeber anything we do with the left padding in the project?

Before I was thinking it was something related to TABS (replacing with spaces) but I looked at my file and didn't find any.

**Comment by jzabroski** [comment]
Take your time.  My point is more to do with whether the EscapeCharacters collection should include all characters. https://docs.oracle.com/cd/B28359_01/appdev.111/b28370/literal.htm#LNPLS01326

> A character literal is an individual character enclosed by single quotes (apostrophes). Character literals include all the printable characters in the PL/SQL character set: letters, numerals, spaces, and special symbols. PL/SQL is case sensitive within character literals. For example, PL/SQL considers the literals 'Q' and 'q' to be different. For more information, see Character Literals.
> 
> A string literal is a sequence of zero or more characters enclosed by single quotes. The null string ('') contains zero characters. A string literal can hold up to 32,767 characters. PL/SQL is case sensitive within string literals. For example, PL/SQL considers the literals 'white' and 'White' to be different.
> 
> To represent an apostrophe within a string, enter two single quotes instead of one. For literals where doubling the quotes is inconvenient or hard to read, you can designate an escape character using the notation q'esc_char ... esc_char'. This escape character must not occur anywhere else inside the string.

Other stuff: It appears Oracle supports changing the quote character.  https://livesql.oracle.com/apex/livesql/file/content_CIREYU9EA54EOKQ7LAMZKRF6P.html

**Comment by fairking** [comment]
Got some news
I digged into the rabbit hole and found that the issue is caused by `Oracle.ManagedDataAccess.Client.OracleCommand`. If I copy a query from the command it runs in the sql manager with no issues, but the step into the command execution throws an exception `string literal too long`:
image

**Comment by fairking** [comment]
I am giving up. I cannot figure out how to trace the failed query in the profiler. Those spaces I was mentioned in the above comment could be related to the terminal. But `.replace(" ", "")` definitely worked. So I have no idea what is going on.

**Comment by jzabroski** [comment]
@fairking Thanks, I will definitely pick this up at some point this week.  Initially Fabien did have 3900 characters.  I think you've provided enough info for me to figure out the issue.

In the mean time, is your UTF8 workaround a viable workaround?  Thanks

**Comment by fairking** [comment]
What do you mean UTF8 ? My current workaround is `.Replace(" ", "")` but it changes the content of the original document so I assume it is temporary.

**Comment by jzabroski** [comment]
I'm going to try to review this today - yesterday was a super long day at work.

**Comment by jzabroski** [comment]
I haven't forgotten about this PR.  Close to accepting it. I started a code spike using ParseCombiningCharacters to understand how to future proof this using standard APIs.

**Comment by fairking** [comment]
I would do one extra test (not sure it is possible with unit tests but can be done manually). To save the string (eg. my example) and then pull it back from the db and check the string is the same.

**Comment by fairking** [comment]
I did the manual test. Seems it is working. I have included tab and single quotes to make sure everything comes back with the same shape. Feel free to merge it down if you have no complains.
image

**Comment by fairking** [comment]
Hi @jzabroski 
Are you going to include this fix into 3.2.8 ? Cannot see any milestones tagged.
One more thing you can use Squash Commit to make your master branch more clear:
image

**Comment by jzabroski** [comment]
@fairking I don't squash.  Not a believer.

I added the milestone - it's in the non-public draft release notes.  Thank you for catching that.  I'm pretty close to release 3.2.8.  Just refactoring some logic I wrote last week to make it cleaner, then releasing it.

**Pull request merged**
