### PR TITLE
Added ability for TagsAttribute to be applied to and inherited from i…

### PR DESCRIPTION
**Pull request by zendever**
…nterfaces. Applies to issue #1026

### CODE REVIEW

**Comment by fubar-coder** [comment]
This PR looks good to me. What do you think, @jzabroski .

**Comment by jzabroski** [comment]
:shipit: - But can @zendever  please also update the documentation for tags?  Michael, the documentation is under : https://github.com/fluentmigrator/documentation/blob/master/articles/migration/migration-filter-tags.md

**Comment by jzabroski** [comment]
@zendever @mrmikal I'm wondering if this PR caused regressions in the 3.2.4 release around running migrations without any Tags. Have you tried 3.2.4, and do any of your migrations have zero tags?

**Comment by jzabroski** [comment]
See #1211

**Comment by jzabroski** [comment]
@zendever @mrmikal Actually, it's possible you fixed a bug, but that bug likely breaks a lot of users (including a project I work on).  Investigating further.

**Comment by zendever** [comment]
@jzabroski - If I did somehow unintentionally break something for you, I apologize. I haven't tried 3.2.4. Looking at the change set #1027 , I'm not exactly sure how the functionality was materially changed from how the Tags feature was implemented previously, aside from adding the union of the inheritance chain. Let me take a look at the latest version and see what's what.

**Comment by jzabroski** [comment]
Thanks, I've been looking at this for a couple of hours trying to understand what's being reported.

**Comment by jzabroski** [comment]
@zendever After much debugging, I think the issue reported is a false positive.  I think you did great work... but there was only a handful of commits in the last release and this was the only one that touched tags, so it seemed reasonable place to look.  Sorry for the grief.  I owe you a beer.

**Comment by zendever** [comment]
@jzabroski - No worries. Glad to hear it was a false positive. In looking at the unit tests for the DefaultMigrationInformationLoader, I see that only marginal testing was done there, but it did conclude that untagged migrations would be included by default. In researching, I modified the tests to use the DefaultMigrationConventions.Instance and added a few extra tests surrounding compounding and inheriting tags and they all ended up passing too...so I figured it may have been something else. I had been using a fork for the longest time and hadn't really pulled from the origin in a long while. It's good to see that everything is still working. Looks like now, I can probably pull in the full release!

**Comment by jzabroski** [comment]
@zendever If you want to help improve FluentMigrator, your contributions would be extremely valuable.  Most of my time is spent trying to be the [KeeperOfTheFlame](https://wiki.c2.com/?ArchitectAsKeeperOfTheFlame), although I'm optimistic this year I will get a chance to write code, as some of the trickier problems are solved.

The main issue I want help with is re-doing how connection management works, to allow passwordless connections and better decouple FluentMigrator transactions from connection transactions via unit of work pattern.  I think someone of your skill level likely could tackle this.

As for your additional tests, please feel free to submit a PR to contribute them.  I feel those tests need to be re-written as orthogonal array testing strategies (OATS) in order to correctly guarantee coverage of all pairwise combinations.  Last night, I went through all the various ways you could conceivably filter migrations, and just in the default code, there is `MigrationConstraintAttribute`, `MigrationTraitAttribute`, `TagsAttribute`, and `MaintenanceMigration` vs. `Profile` vs `Migration` (regular).

**Pull request merged**
