### PR TITLE
Replace MySql.Data to MySqlConnector

### PR DESCRIPTION
**Pull request by lillo42**
Replace [MySql.Data](https://github.com/mysql/mysql-connector-net) to [MySqlConnector](https://github.com/mysql-net/MySqlConnector) because `MySqlConnector` has better support and some issues on `MySql.Data` has been already fixed in `MySqlConnector ` see: https://mysqlconnector.net/tutorials/migrating-from-connector-net/

### CODE REVIEW

**Comment by lillo42** [comment]
This PR will fixed this issue too https://github.com/fluentmigrator/fluentmigrator/issues/1670

**Comment by jzabroski** [comment]
Hey @lillo42 . I will try to merge this this weekend.  I've got like 38 failing tests in a merge of Snowflake and Postgres changes from develop branch to main branch so that we can release 4.0.

**Comment by 01aroe** [comment]
@jzabroski if you are able to get this PR merged soon that would be great :)

**Comment by 01aroe** [comment]
Any update on getting this PR merged? Thanks

**Comment by jzabroski** [comment]
I should get to it by end of this month. Finally winding down a large project at work.

**Comment by jzabroski** [comment]
I just updated your PR to reflect the changes that will go into 4.0.0 release. Assuming azure pipelines passes i will merge this shortly

**Comment by jzabroski** [comment]
This is now merged.

**Pull request merged**
