### PR TITLE
Update FluentMigrator.DotNet.Cli to netcoreapp2.2

### PR DESCRIPTION
**Pull request by bdebaere**
Update FluentMigrator.DotNet.Cli to netcoreapp2.2.

### CODE REVIEW

**Comment by fubar-coder** [comment]
Delayed until the Travis-CI build server problems are resolved. See dotnet/corefx#36881

**Comment by jzabroski** [comment]
@fubar-coder Given the related issue is closed in CodeFx, can we merge this now?

**Comment by fubar-coder** [comment]
You may try to merge this, but you also have to update the `.travis.yml` to .NET Core 2.2. Otherwise the build will just fail.

**Comment by espumita** [comment]
Any news?

**Comment by jzabroski** [comment]
We're trying to look into why Travis CI gives us some headaches.  If you
have lots of experience w/ Travis, would love help.  As example, PR #1042
timed out for some reason and we don't know why yet.

**Comment by jzabroski** [comment]
@bdebaere Any interest in fixing .travis.yml to support .net core 2.2?

https://github.com/fluentmigrator/fluentmigrator/blob/f3aabd0ba430a3e8bd211fd8fd55b66f31481590/.travis.yml#L5

**Comment by BigYellowHammer** [comment]
can we trigger checks again now once we have new pipelines in place?

**Comment by bdebaere** [comment]
@jzabroski I have no idea how travis works, so I merely updated the value you mentioned. If there's anything else, please let me know.

**Comment by jzabroski** [comment]
We are moving to Azure DevOps pipeline, I think. It's not official yet but I think we're getting close.

**Comment by fubar-coder** [comment]
We should consider updating to 3.0 instead.

**Comment by jzabroski** [comment]
Closing this - I thought we merged in the changes from 4.0 develop branch into master, but it looks like we didn't.  I will create a new issue and PR to do just that.

**Pull request closed without merging**
