### PR TITLE
Adjusted SQLite types to be more accurate

### PR DESCRIPTION
**Pull request by elken**

### CODE REVIEW

**Comment by fubar-coder** [comment]
Isn't TINYINT for example internally the same as INTEGER?

**Comment by elken** [comment]
Essentially, but the significance was mostly `BIGINT` for `AsInt64` migrations. Keeps things more consistent.

**Comment by fubar-coder** [comment]
This breaks compatibility with SQLite 2, so maybe I should separately support both SQLite2 and SQLite3...

**Comment by elken** [comment]
Couldn't hurt to, but that's up to you. I can't imagine many people requiring sqlite2 so shouldn't be much more work. 

⁣Sent from Blue ​

**Comment by elken** [comment]
Maybe pass the version in to `AddSqlite` and use that to check.

**Comment by elken** [comment]
See #949

**Comment by jzabroski** [comment]
@fubar-coder I say we drop support for sqlite2 and push this forward. Agree or disagree?

**Comment by fubar-coder** [comment]
I agree. I haven't seen uses of  sqlite 2 for a while, so I guess that it's safe to remove support for it.

**Comment by jzabroski** [comment]
@elken  Sorry for the prolonged delay.  I recently got involved to help @fubar-coder with this project, and we're slowly making sense of a strategy to go through the backlog, decide what constitutes a good idea/direction for the project, etc.

This will hopefully be merged in the next two weeks, but I am going on my honeymoon August 4th.  Ideally, no later than August 31st.  One thing that would help is if you could update your branch to be even with the FM develop branch (4.0 branch).

**Comment by elken** [comment]
I'll take a look tmrw

**Comment by elken** [comment]
That should be good. Anything else let me know. 

Enjoy the honeymoon.

**Comment by jzabroski** [comment]
Hmm... it looks like the [tests failed](https://travis-ci.org/fluentmigrator/fluentmigrator/builds/563211807?utm_source=github_status&utm_medium=notification) for some reason:

```
!!! Error
Test run in progress...!!! Error
Test run in progress...  ! CanUseCustomVersionInfo [10ms]
Test run in progress...  ! EnsureThatVarCharColumnsHaveLengthOf40 [1ms]
Test run in progress...
The job exceeded the maximum time limit for jobs, and has been terminated.
```

Thanks for the well wishes!  I really appreciate it.

**Comment by elken** [comment]
My bad, I just did a blind merge. I'll see what I can do tmrw.

**Comment by jzabroski** [comment]
It might also just be that it ran out of time in the middle of execution of those two tests (concurrently).   Travis-CI is not super great with error messages, as compared with say TeamCity.

**Comment by elken** [comment]
Could be, I just stick with Gitlab myself.

**Comment by jzabroski** [comment]
Thanks.  I posted on the Travis CI gitter channel, but the thing puzzling me is why some builds take 6 minutes and others take 30+ minutes.  Can noisy neighbors really be that noisy?

**Comment by elken** [comment]
Not sure, could be. 

⁣Regards,
Ellis Kenyő

GitLab | GitHub | Keybase | elken.me​

**Comment by jzabroski** [comment]
It looks like a specific test is hanging the build for some reason.  The build errored at 33m, and then Travis continued to print status messages "Test run in progress."

**Comment by elken** [comment]
I'll run a few tests on gitlab

⁣Regards,
Ellis Kenyő

GitLab | GitHub | Keybase | elken.me​

**Comment by jzabroski** [comment]
@fubar-coder We should revisit merging this now that Azure DevOps pipeline seems to be stable.

**Comment by jzabroski** [comment]
@elken  I think we have PRs to this repository figured out - do you want to update the PR so we can merge it?  Sorry for the delay - sorting out CI/CD processes for open source projects is a pain in the neck, as we're not looking to spend money to support something that's free.

**Comment by jzabroski** [comment]
@elken Nevermind, I merged it - I'll fix anything that is broken. Just trying to reduce our PR backlog as I think it looks bad to see so many open PRs stagnate.

**Pull request merged**
