### PR TITLE
Changed Nant build to use FluentMigrator.sln

### PR DESCRIPTION
**Pull request by escarls**

### CODE REVIEW

**Comment by escarls** [comment]
The Nant build in TC also build fine:
https://teamcity.jetbrains.com/viewLog.html?tab=buildLog&buildTypeId=bt82&buildId=996903

**Comment by fubar-coder** [comment]
This are very good news. Can you please add a document to the source code that explains what needs to be done to setup a build server (maybe also for Travis CI)? What are the prerequisites and what are the common tripping points? Thank you again for your work!

**Comment by escarls** [comment]
I will add to Wiki if/when I setup my own build server.
So far, I've just created my own account at [travis-ci](https://travis-ci.org/) to be able to test before my PRs.
I'm thinking about a teamcity setup though, as it seems I cannot create my own projects at the same TS server as this project is using.

**Comment by escarls** [comment]
There is also a question, maybe we should drop the TC server?
Seems it have issues integrating with GitHub now:
"Commit Status Publisher error. Publisher: githubStatusPublisher(https://teamcity.jetbrains.com/viewLog.html?buildId=996903&buildTypeId=bt82). Failed to complete request to GitHub. Status: HTTP/1.1 401 Unauthorized"

And I do think that Travis will have what we need to do the CI.

**Comment by escarls** [comment]
This PR is part of my PRs to solve #738.

**Comment by fubar-coder** [comment]
I will try to set up the GitHub integration for another project. Maybe I can find a solution.

**Comment by escarls** [comment]
@fubar-coder any chance you could look at this, so I can make a pr to fix the Travis builds on Trusty?

**Comment by fubar-coder** [comment]
Obsolete now with Travis supporting Mono/.NET Core/MSBuild.

**Pull request closed without merging**
