### PR TITLE
First cut of redshift provider

### PR DESCRIPTION
**Pull request by izevaka**
I have experimented with different designs, starting with inheriting all of redshift classes from postgres. This required multiple changes to postgres classes (like passthrough constructors), but had the benefit of redshift classes being very minimal. I then realised that this is not how the rest of the DB specialisation classes were written. Also this would tightly couple the two, making changes to postgres more difficult. 

I then duplicated the lot and changed the bits that needed changing. This keeps two providers separate but results in a whole bunch of duplicated code in the Runner project.

The next iteration was creating a whole bunch of PostgresBase classes and then have Postgres and Redshift generator classes inherit from common Postgres base classes. The duplication within `Processor` namespace is pretty minimal and IMHO didn't warrant base classes.
- Introduce PostgresBase... classes in the Generators namespace.
- Change Postgres classes in the Generators namespace to inherit from PostgresBase.
- New set of Redshift classes that also inherit from PostgresBase.
- New lot of test classes for Redshift (some duplication there, however a lot of tests are different - those ones around indexes, sequences and anything generating serial columns.
- No integration tests yet.

### CODE REVIEW

**Comment by izevaka** [comment]
I am happy with this now. Highlights of the change:

* Introduce `PostgresBase...` classes in the `Generators` namespace.
* Change Postgres classes  in the `Generators` namespace to inherit from `PostgresBase`.
* New set of Redshift classes that also inherit from `PostgresBase`.
* New lot of test classes for Redshift (some duplication there, however some tests are different - those ones around indexes, sequences and anything generating `serial` columns.
* No integration tests yet.

**Comment by gvessere** [comment]
Hi, it would be good to have a release with these improvements. what are the upcoming releases looking like?

**Comment by tommarien** [comment]
@gvessere Hi there

Next release will be 1.6.1 (so just fixes, release data approx 10 nov 2015)

After that 1.7.0 which can include this, but i have no idea yet on release date

**Comment by pallie83** [comment]
Hi There,

Do you have any idea if release 1.7.0 of FluentMIgrator will include this feature, and when 1.7.0 will be released? We are looking into using FluentMigrator for Redshift database migrations, so would be good to have a timeframe on this feature if that's possbile....

thanks.

**Comment by yuripallada** [comment]
Hi, is there any news or a timeframe with regards to when this pull request will be merged?

**Comment by fubar-coder** [comment]
TBH: I currently don't have much time and I don't have an ETA for 1.7.0 yet.

**Comment by fubar-coder** [comment]
Your changes have been incorporated into the release/2.0.0 branch

**Pull request closed without merging**
