### PR TITLE
allowed for TagsAttribute to match by inheritance

### PR DESCRIPTION
**Pull request by zendever**
Solves issue #626 and allows for Tags to be inherited

### CODE REVIEW

**Comment by zendever** [comment]
Solves issue #625 and allows for token dictionary to be passed to Script and EmbeddedScript

**Comment by fubar-coder** [comment]
@zendever Can you please create a new pull request for #625 with only minimal changes (i.e. without changes to the project files)?

**Comment by zendever** [comment]
@fubar-coder I went ahead and modified the project files back to the way that they were (and added the necessary files). This should have what you need, and it looks to be passing the checks.

**Comment by fubar-coder** [comment]
Thank you, that is very helpful. I don't have access to a PC for the next two weeks, but I'll take a look afterwards.

**Comment by fubar-coder** [comment]
Your changes have been incorporated into the release/2.0.0 branch

**Pull request closed without merging**
